### ISSUE TITLE
No getters and setters

### ISSUE THREAD

**Issue by vbhambhu** [NIT-Software/Modern-Ecommerce#8]
Hi I imported application to intelij. Created database and change config. 

Seems like no getter and setter for model classes. I am getting 
```

Error:(37, 52) java: cannot find symbol
  symbol:   method getUserId()
  location: variable userToken of type com.nitsoft.ecommerce.database.model.UserToken
```

**Comment by PaskoZhelev** [comment]
That is because they use the Project Lombok library which generates the getters and setters automatically when you add annotations to the model class.

Check whether the Lombok library is imported correctly and this issue would be resolved.

**Comment by vbhambhu** [comment]
Thanks, It was imported successfully but for some reason, it was not working. After updating dependency to below worked fine


```
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.20</version>
    <scope>provided</scope>
</dependency>
```
